import 'dart:typed_data';

import 'package:intl/intl.dart';
import 'package:konnectrent/core/utils/format_utils.dart';
import 'package:konnectrent/domain/entities/rent_calc_result.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

/// Runs inside a compute() isolate — no Flutter widget dependencies.
class PdfGenerator {
  const PdfGenerator._();

  /// Entry point called via compute(PdfGenerator.build, result).
  static Future<Uint8List> build(RentCalcResult result) async {
    final doc = pw.Document();

    final verdictLabel = result.verdict.name == 'rentWins'
        ? 'Renting is cheaper'
        : result.verdict.name == 'buyWins'
            ? 'Buying is cheaper'
            : 'Break-even';

    final generatedDate =
        DateFormat('dd MMM yyyy, hh:mm a').format(DateTime.now());

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        header: (_) => _buildHeader(generatedDate),
        footer: (_) => _buildFooter(),
        build: (ctx) => [
          _buildVerdictSection(result, verdictLabel),
          pw.SizedBox(height: 16),
          _buildSummaryTable(result),
          pw.SizedBox(height: 16),
          _buildAmortizationTable(result),
          pw.SizedBox(height: 16),
          _buildDisclaimer(),
        ],
      ),
    );

    return doc.save();
  }

  static pw.Widget _buildHeader(String date) => pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                'KonnectRent — Rent vs Buy Report',
                style: pw.TextStyle(
                  fontSize: 16,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.teal700,
                ),
              ),
              pw.Text(date, style: const pw.TextStyle(fontSize: 10)),
            ],
          ),
          pw.Divider(color: PdfColors.teal700),
          pw.SizedBox(height: 4),
        ],
      );

  static pw.Widget _buildFooter() => pw.Column(
        children: [
          pw.Divider(),
          pw.Text(
            'Generated by KonnectRent. For informational purposes only.',
            style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
          ),
        ],
      );

  static pw.Widget _buildVerdictSection(
    RentCalcResult result,
    String verdictLabel,
  ) =>
      pw.Container(
        padding: const pw.EdgeInsets.all(16),
        decoration: pw.BoxDecoration(
          color: PdfColors.teal50,
          borderRadius: pw.BorderRadius.circular(8),
        ),
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              verdictLabel,
              style: pw.TextStyle(
                fontSize: 20,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.teal800,
              ),
            ),
            pw.SizedBox(height: 8),
            pw.Text(
              'You save ${FormatUtils.toIndianCurrency(result.rentAdvantage.abs())} over 10 years',
              style: const pw.TextStyle(fontSize: 13),
            ),
            pw.SizedBox(height: 4),
            pw.Text(
              'Monthly EMI: ${FormatUtils.toEmi(result.monthlyEmi)}',
              style: pw.TextStyle(
                fontSize: 13,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
            if (result.breakEvenYear != null) ...[
              pw.SizedBox(height: 4),
              pw.Text(
                'Break-even year: ${result.breakEvenYear}',
                style: const pw.TextStyle(fontSize: 12),
              ),
            ],
          ],
        ),
      );

  static pw.Widget _buildSummaryTable(RentCalcResult result) {
    final input = result.input;
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Input Summary',
          style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 8),
        pw.Table(
          border: pw.TableBorder.all(color: PdfColors.grey300),
          columnWidths: {
            0: const pw.FlexColumnWidth(2),
            1: const pw.FlexColumnWidth(2),
            2: const pw.FlexColumnWidth(2),
            3: const pw.FlexColumnWidth(2),
          },
          children: [
            _tableHeaderRow(['Parameter', 'Value', 'Parameter', 'Value']),
            _tableRow(['Monthly Rent', FormatUtils.toIndianCurrency(input.monthlyRent), 'Property Price', FormatUtils.toIndianCurrency(input.propertyPrice)]),
            _tableRow(['Rent Increase', FormatUtils.toPercent(input.annualRentIncrease), 'Down Payment', FormatUtils.toIndianCurrency(input.downPayment)]),
            _tableRow(['—', '—', 'Interest Rate', FormatUtils.toPercent(input.annualInterestRate)]),
            _tableRow(['—', '—', 'Loan Tenure', '${input.loanTenureYears} years']),
            _tableRow(['—', '—', 'Appreciation', FormatUtils.toPercent(input.annualAppreciation)]),
            _tableRow(['Opportunity Cost', FormatUtils.toPercent(input.opportunityCostRate), 'Maintenance/yr', FormatUtils.toIndianCurrency(input.annualMaintenance)]),
          ],
        ),
        pw.SizedBox(height: 12),
        pw.Text(
          'Cost Comparison',
          style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 8),
        pw.Table(
          border: pw.TableBorder.all(color: PdfColors.grey300),
          children: [
            _tableHeaderRow(['Horizon', 'Rent Total', 'Buy Total', 'Difference']),
            _tableRow([
              '10 Years',
              FormatUtils.toIndianCurrency(result.tenYearRentTotal),
              FormatUtils.toIndianCurrency(result.tenYearBuyTotal),
              FormatUtils.toIndianCurrency((result.tenYearBuyTotal - result.tenYearRentTotal).abs()),
            ]),
            _tableRow([
              '20 Years',
              FormatUtils.toIndianCurrency(result.twentyYearRentTotal),
              FormatUtils.toIndianCurrency(result.twentyYearBuyTotal),
              FormatUtils.toIndianCurrency((result.twentyYearBuyTotal - result.twentyYearRentTotal).abs()),
            ]),
          ],
        ),
      ],
    );
  }

  static pw.Widget _buildAmortizationTable(RentCalcResult result) =>
      pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'Loan Amortization Schedule',
            style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 8),
          pw.Table(
            border: pw.TableBorder.all(color: PdfColors.grey300),
            children: [
              _tableHeaderRow(['Year', 'Principal Paid', 'Interest Paid', 'Balance']),
              ...result.schedule.map(
                (row) => _tableRow([
                  '${row.year}',
                  FormatUtils.toIndianCurrency(row.principalPaid),
                  FormatUtils.toIndianCurrency(row.interestPaid),
                  FormatUtils.toIndianCurrency(row.remainingBalance),
                ]),
              ),
            ],
          ),
        ],
      );

  static pw.Widget _buildDisclaimer() => pw.Container(
        padding: const pw.EdgeInsets.all(8),
        decoration: pw.BoxDecoration(
          color: PdfColors.grey100,
          borderRadius: pw.BorderRadius.circular(4),
        ),
        child: pw.Text(
          'Disclaimer: All calculations are for informational purposes only and do not '
          'constitute financial advice. Consult a qualified financial advisor before '
          'making property purchase decisions.',
          style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
        ),
      );

  static pw.TableRow _tableHeaderRow(List<String> cells) => pw.TableRow(
        decoration: const pw.BoxDecoration(color: PdfColors.teal700),
        children: cells
            .map(
              (c) => pw.Padding(
                padding: const pw.EdgeInsets.all(6),
                child: pw.Text(
                  c,
                  style: pw.TextStyle(
                    color: PdfColors.white,
                    fontWeight: pw.FontWeight.bold,
                    fontSize: 10,
                  ),
                ),
              ),
            )
            .toList(),
      );

  static pw.TableRow _tableRow(List<String> cells) => pw.TableRow(
        children: cells
            .map(
              (c) => pw.Padding(
                padding: const pw.EdgeInsets.all(5),
                child: pw.Text(c, style: const pw.TextStyle(fontSize: 10)),
              ),
            )
            .toList(),
      );
}
